version: 2
jobs:
  build:
    working_directory: ~/my-project
    docker:
      - image: circleci/node:8-browsers
    steps:
      - checkout
      - restore_cache:
          key: my-project-{{ .Branch }}-{{ checksum "package-lock.json" }}
      - run: yarn
      - save_cache:
          key: my-project-{{ .Branch }}-{{ checksum "package-lock.json" }}
          paths:
            - "node_modules"
      - run: yarn test -- --no-watch --no-progress --browsers=ChromeHeadless
      - run: yarn e2e -- --protractor-config=e2e/protractor-ci.conf.js
      - run:
            name: Build Succeeds
            command: curl https://maker.ifttt.com/trigger/green_light_on/with/key/pS-ooPZ4dXuyIs8L-JLBZH0qc5poEM1ii9HpFeAOSp9
            when: on_success
      - run:
            name: Build Fails
            command: curl https://maker.ifttt.com/trigger/red_light_on/with/key/pS-ooPZ4dXuyIs8L-JLBZH0qc5poEM1ii9HpFeAOSp9
            when: on_fail
